### PR TITLE
Support for Ambit3 Vertical, Traverse & Traverse Alpha. Ambit3 driver refactor and legacy firmware support.

### PR DESCRIPTION
**Pull request by wbarnard**
Adds support for Ambit3 Vertical, Traverse and Traverse Alpha watch models.

Adds support for Ambit3 firmware v2.2.16 and fixes broken support for other legacy fw versions.

Refactoring and parameterisation of Ambit3 driver.

### CODE REVIEW

**Comment by manisandro** [comment]
Thanks! I'll leave it open for a couple of days for interested people to review, then if nothing else I'll merge it.

**Comment by manisandro** [comment]
Merged, thanks!

**Comment by dp999** [comment]
Hi, 
I still have troubles connecting my traverse with the latest commit.
Gui says: Device Suunto Traverse 8422something device not yet supported.
Do you any further suggestions?

Thanks for your efforts!

**Comment by wbarnard** [comment]
I have added support in the driver, there may be something more we need to do to enable that in the GUI.

Also, there are a couple of Traverse legacy firmware versions (1.5.4 & 2.0.5)  that are still not supported, which firmware are you running on the watch?

**Comment by wbarnard** [comment]
That firmware version is supported.

To figure out what is happening, you can build and run ambitconsole in openambit/src/example. This will give a detailed log.

**Pull request merged**
