### PR TITLE
Build with Qt5 by default

### PR DESCRIPTION
**Pull request by damienrg**

### CODE REVIEW

**Comment by damienrg** [comment]
Removing Qt4 will be done in a following PR.

**Comment by damienrg** [comment]
Removing Qt4 will be done in a following PR.

**Comment by manisandro** [comment]
Thanks!

**Comment by bubulle** [comment]
This is *exactly* the one I need in order to revive Openambit in
Debian (and therefore Ubuntu). Thanks to damienrg

I would really love to see an official release with that one. Whether
or not it should also include the patch dropping Qt4 support is
another story (I would be in favor of it too).

**Comment by centic9** [comment]
Me too, my ppa-build for Ubuntu is accumulating more and more stuff, would be nice to being able to rebase it on a more recent Debian package again.

**Pull request merged**
