### PR TITLE
Add support for registering new device to movescount.com

### PR DESCRIPTION
**Pull request by alkino**

### CODE REVIEW

**Comment by alkino** [comment]
I rob it to @natanojl, it fix #73 
I rebase it.
I had "FirmwareVersion" field as movescount ask for it.

**Comment by alkino** [comment]
It has been tested successfully with my Ambit3 Peak.

**Comment by centic9** [comment]
Reopening as it seems this was not applied, although it might not be useful for too long with the announced EOL of the Movescount website in January...

**Comment by marguslt** [comment]
> announced EOL of the Movescount website in January...

To clarify, Movecount service & web closing was announced as "earliest in summer 2020"
By the end of 2019 they promised to pull Movescount **mobile** apps from app stores while still keeping existing installations functional.

Though I have some reasons to doubt they'll actually stick to those plans, but there hasn't been official update on this since May.
https://www.suunto.com/Content-pages/digital-service-transition/

**Pull request closed without merging**
