### PR TITLE
Sync navigation items (POIs / routes) (ambit2) - fixes #125

### LINKED ISSUE #125: Sync navigation items (POIs / routes) (ambit2)
I'm working on support for sync of the navigation items POIs (waypoint) and routes between device and movescount.

This is ongoing work, and at current stage it will **sync POIs only**, and **delete all routes** from device (due to protocol limits).

You can find my fork at: https://github.com/landas/openambit

It has a lot of added debug messages as it is ongoing work.

**Next stages:**
1) More investigation in the route protocol.
2) Fix better driver support. (driver API for navigation read/write WILL be changed)
3) Implement routes
4) Sync of personal settings 

**POIs sync:**
1) Download POIs (settings) from moves link 
2) Sync POIs added or deleted on device to movescount
3) Download POIs (settings) from moves link
4) Delete all waypoint/routes from device (only known protocol command)
5) Add downloaded (3) POIs from moveslink to device.

_The sync sequence is adopted from Windows movelinks2_

### PR DESCRIPTION
**Pull request by landas**
## Summary
This pull request fixes #125 .

I have done extensive testing and I have never experienced any crashes on my computer or any problems on my Ambit. I have tested small routes, big routes, 1 route, many routes with a lot of data.

*Waypoint / routepoint  will sync* if the user has enabled "sync logs with movescount". I will do some clean up in settings code after I have merged @superdupersvard code.

## Known sources of uncertainty
How the ambit calculate the distance (this is an important part of sending routepoints to the device) is not 100% certain. I have used the standard [Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula) and a earth radius of 6367km. This worked perfect in my tests of very long routes in south of Norway. I dont know if this is the correct formula used inside watch. I don't know if the watch use different earth radius on different points on the earth :smile: 

I need feed back from users to know. For me the formula and the erath radius work "_perfect_" within 5 meters error margin on a 200km route.

https://github.com/openambitproject/openambit/compare/master...landas:master#diff-9b9ed44590de637db939610f2167c9ad

## Some documentation on my research of the protocol
[Ambit waypoints route documentation.zip](https://github.com/openambitproject/openambit/files/888713/Ambit.waypoints.route.documentation.zip)

## All the structs for sending data to the ambit is better documented in the code
https://github.com/openambitproject/openambit/compare/master...landas:master#diff-88c7caf5ec8b5f03eba8965921806924

## Last story
When developing and testing adding of routepoints, I had an error in my for loop so my code added routepoints-data way beyond the memory space for routepoints inside ambit. The result was it overwrite some of my sports mode with garbage data, but the ambit was all happy. It just reset itself to one default sport mode. :smile:

So I think this watch is difficult to brick.

### CODE REVIEW

**Comment by landas** [comment]
I feel confident that this code can merge into the master now.
I'm happy to fix if anyone reports any problems.

After we have merged @superdupersvard and I have cleaned up some code in settings, maybe we should make it a new version and inform distributions to add the new version?

**Comment by manisandro** [comment]
Ok cool, thanks! Yeah sure it would be high time for a new version :)

**Comment by mbernasocchi** [comment]
great stuff guys :)

**Comment by vdca** [comment]
Thanks for this great piece of software. I have haven't managed to get route-sync working with openambit 0.4 and an ambit3. Is this supposed to work only for routes created via movescount, or is it possible to write say a gpx file directly to the watch?

**Pull request merged**
