### PR TITLE
Added custom mode (Superdupersvard)

### PR DESCRIPTION
**Pull request by landas**
The only thing I have done is:
1) Test: add and remove one custom mode
2) Fixed merge conflicts
3) Removed a few line of debug messages, and renamed a couple of function / struct names.

### CODE REVIEW

**Comment by manisandro** [comment]
I suppose custom modes are custom sport modes created via movescount?

**Comment by landas** [comment]
Hi, this is correct.

If you want i can rename all files, struct and function names from ..custom_modes.. to "..custom_sport_modes.." or "..sport_modes..".

**Comment by manisandro** [comment]
If not too much work, I guess it would be a helpful hint to quickly identify the purpose of the code.

**Comment by landas** [comment]
I will try to do it later today before I go on holiday.

**Comment by landas** [comment]
Updated pull request

**Comment by manisandro** [comment]
Thanks!

**Comment by landas** [comment]
Fixes #21

**Pull request merged**
