### PR TITLE
Enable handling IBI data as heart rate data in openambit2gpx

### PR DESCRIPTION
**Pull request by vascotenner**
Solves #181: openambit2gpx can now handle IBI data as heart rate data 

And has already merge PR #209: python 3 support

### CODE REVIEW

**Comment by vascotenner** [comment]
Is there any interest in merging this to master?

**Comment by centic9** [comment]
Do you do the IBI->HR conversion because the HR-Data is missing otherwise or do you think the IBI value is "better"?

If the former, I would probably try to use "HR" whenever it is available and fall back to IBI only when "HR" is missing to not cause a change compared to all previously generated GPX files. 

In a quick test it seems generated HR values are slightly different for large parts of the resulting GPX-files, not just some small time-shift.

**Comment by vascotenner** [comment]
I use ibi because the hr data was missing when i tried openambit with my ambit3.

Dominik Stadler <notifications@github.com> schreef op February 14, 2021 9:31:25 PM UTC:

**Comment by centic9** [comment]
Ok, so it seems to be depending on the device if the HR samples are available or not. 

Maybe we can check for the Device in the tag DeviceInfo and choose "HR" or "IBI" based on this to not change produced files for the Devices that properly have HR included already.

**Comment by vascotenner** [comment]
Good suggestion, i will have a look to it next week.

Dominik Stadler <notifications@github.com> schreef op February 17, 2021 6:28:12 PM UTC:

**Comment by marguslt** [comment]
@centic9 ,
> Ok, so it seems to be depending on the device if the HR samples are available or not.
> 
> Maybe we can check for the Device in the tag DeviceInfo and choose "HR" or "IBI" based on this to not change produced files for the Devices that properly have HR included already.

Not just the watch, it's also depending on used heart rate monitor, at least for Ambit3 - https://github.com/openambitproject/openambit/issues/181#issuecomment-363391669 and following comments, until Mio Link. 

Suunto Smart ANT belts and Smart Sensor (Bluetooth , for Ambit3 range ) are always sending out IBI values. As far as I know, it's the same for most other ANT+ & Bluetooth chest HRMs as well, at least those by Polar & Garmin. 
While optical HRMs (Mio Link, Scosche Rhythm, Polar OH1 etc) just transfer Heart Rate.

On the other hand..  libambit driver for Ambit3 might have a role here: 
I know for sure I didn't have HR values in Openambit logs for my Ambit3 back then (Feb 2018), just IBI stream; but I found few Moveslink2 SML files from the same watch and those actually include both HR & IBI. Though those Moveslink2 files are newer (Dec 2019) and I had switched from Suunto Smart Sensor belt to Polar H10, not sure if this could make a difference.

**Pull request closed without merging**
