### PR TITLE
Bugreport menu + --version flag

### PR DESCRIPTION
**Pull request by landas**
Hi,

**Added a 'report bug' to app menu**
With link to https://github.com/openambitproject/openambit/issues

**Added support for --version flag**
The problem is it will always show Version HEAD, due to "set (OPENAMBIT_VERSION HEAD)"  in CMakeLists.txt

https://github.com/openambitproject/openambit/blob/ed204af960ca3b1ccc6e1f12cc586ddb639d4376/src/openambit/CMakeLists.txt#L4

### CODE REVIEW

**Comment by manisandro** [comment]
We should definitely looks at release a new version, and then replace HEAD with the appropriate version ;) Do you have other stuff in the pipeline?
By the way, do you want to become a project member?

**Comment by landas** [comment]
I would be happy to be a project member. :)

No more updates I can think of in the pipeline for now. 
Could be interesting to see if I can help out with ambit3 support but that must go for another release.

**Comment by manisandro** [comment]
@mbernasocchi Could you please add @landas as a project member? Thanks!

**Comment by mbernasocchi** [comment]
done

**Pull request merged**
