### PR TITLE
Added norwegian bokmål translation

### PR DESCRIPTION
**Pull request by landas**
I have translated the file to norwegian, but can you tell me how I can enable translation. :)

I tried `lrelease` and moved the .qm file to /usr/share/qt4/translations and  /usr/share/qt5/translations (Ubuntu 16.04) with no luck.

I tried some debug messages in main.cpp, and it confirmed it was looking for ":/translations/openambit_nb_NO"

### CODE REVIEW

**Comment by manisandro** [comment]
Looks like [1][2] the translations are compiled into a resource file which is compiled into the application.

[1] https://github.com/openambitproject/openambit/blob/master/src/openambit/main.cpp#L110
[2] https://github.com/openambitproject/openambit/blob/master/src/openambit/CMakeLists.txt#L122

**Comment by landas** [comment]
Yes it looks like it should, but I dont find any proof of it actual is doing it.

 I have tried the following with no luck:

1) openambit -locale:sv_SE [1]   (both my compiled version and distribution installed version)
2) option(UPDATE_TRANSLATIONS "Update source translation translations/*.ts" ON) [2]
3) copy translation files in all strange places :) (yes it should be a resource)
4) tried to scan the binary executable for translated strings.

[1] https://github.com/openambitproject/openambit/blob/master/src/openambit/translations/openambit_sv.ts
[2] https://github.com/openambitproject/openambit/blob/master/src/openambit/CMakeLists.txt#L122

**Comment by landas** [comment]
Commit 566939b break support for translation in openambit. (on my machine at least)

My knowledge on cmake is not strong. Could someone help me out on this? @manisandro

**Comment by manisandro** [comment]
@landas Apologies, I did indeed break it in 566939b. Fixed in 6e5a8e61899f2f9483923b9868d99e07ab486e31.

**Comment by landas** [comment]
Thanks, then I have tested the translation OK :smile:

**Comment by manisandro** [comment]
Thanks!

**Pull request merged**
